apiVersion: v1
kind: BuildConfig
metadata:
  name: environment-configuration
spec:
  triggers:
  - type: ImageChange
    imageChange:
      lastTriggeredImageID: edr-np.am.lilly.com/jboss-fuse-6/fis-java-openshift
  - type: ConfigChange
  - type: GitHub
    github:
      secret: my-secret
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/SreekanthRamesh/Environment.git
      ref: master
    sourceSecret:
      name: source-secret
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: fis-java-openshift:1.0
      forcePull: true
  output:
    to:
      kind: ImageStreamTag
      name: appname:latest
  resources: {
    }
  postCommit: {
    }
  nodeSelector: null
status:
  lastVersion: 1